version: "3"

services:
  users:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres:12"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "users"
